spring:
  application:
    name: fleetwise
  profiles:
    active: local

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetwise
    username: fleetwise
    password: fleetwise
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false


security:
    jwt:
      secret: fleetwiseai-super-secret-key-256bits-minimum-required-here
      expiration: 86400000


logging:
  level:
    com.fleetwise: DEBUG
    org.springframework.web: DEBUG     

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:fleetwise;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  security:
    user:
      name: test
      password: test
